# -*- coding: utf-8 -*-
"""polynomial_regression_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_Ixll9Yut2vwr-Q9-1q7EcyKKfEdkqs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('Position_Salaries.csv')
df.head()

X = df.iloc[:,1:2].values # independent variables
y = df.iloc[:,-1].values # dependent variable

plt.scatter(X, y)
plt.title('Position Salary')
plt.xlabel('Levels')
plt.ylabel('Salaries')
plt.show();

from sklearn.preprocessing  import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
X_poly

from sklearn.linear_model import LinearRegression
poly_reg = LinearRegression()
poly_reg.fit(X_poly,y)

# Visualising the data set
plt.scatter(X, y)
plt.plot(X, poly_reg.predict(X_poly), color = 'red')
plt.title('Position Salary')
plt.xlabel('Levels')
plt.ylabel('Salaries')
plt.show();

poly_reg.predict(poly.transform([[6.5]]))

